### ISSUE TITLE
Some ideas for implement

### ISSUE THREAD

**Issue by 6aKa** [MusicDin/terraform-kvm-kubespray#6]
Hi, in this issue i try to describe my ideas.

1. copy kubectl to config dir, near admin.conf.
2. by default disable dashboard, and install dashboard using helm provider, and configure after install. I think need install all addons with helm, such as registry, metrics_server.
3. use metallb for cluster balancer.

**Comment by MusicDin** [comment]
Hi, thank you for your ideas, I will try to shortly explain why I'm for or against each one:

1.  Could you provide some arguments why that would be useful? `admin.conf` should be anyway moved to `~/.kube` directory or referenced with environment variable.
2.  I agree that the dashborad should be disabled by default. I will do that shortly and provide an option to enbale it via terraform vars. Since there are so many ways to configure it, I probably won't make any implementation of it (for now). Current dashborad was ment for testing only.
3. MetalLB would be a great addition to the script. I will certently implement it in the future, but to make some sort of general solution it would take me quite some time, which I currently don't have, but I'm planning to add it within a few months.

I will keep your suggestions in mind and am opened for any new ideas you might have.

**Comment by 6aKa** [comment]
1. Kubespray has kubeconfig_localhost and kubectl_localhost settings for copy admin.conf and kubectl files. And I think the best way - forward this option from terraform.tfvars. I want after install move `admin.conf` to `~/.kube` and `kubectl` to `~/bin`.

**Comment by MusicDin** [comment]
I agree, that would be the best way to do it, but I'm afraid that it could result in overwriting files with the same name.

For example, If you would like to run multiple clusters, when the first cluster is created `admin.conf` would be moved to `~/.kube` folder, but when the second cluster is created `admin.conf` could be potentinaly overwriten with the kubeconfig of the second cluster.

That's the reason why I'm avoiding to touch any data outside script's directory.

One solution to this problem could be to name `admin.conf` file diffrently. For example by adding additional terraform variable for kubeconfig name or to use `vm_name_prefix` variable for it, which would result in an error if the vm with the same name is being created. Consequently kubeconfig file won't be created beacuse script won't reach that part of the code.

Another solution would be to make copying/moving kubeconfig to `~/.kube` directory optional (similar to what we did before for known_hosts).

**Comment by 6aKa** [comment]
1. You can make simple. Add `resource "null_resource" "kubectl_binary"` which copy `kubectl` to `config/kubectl` from master node. After `kubespray_create` show formated message like
```
Copy atrifacts after deployment:
mkdir ${HOME}/.kube/
cp `PWD`/config/kubectl ${HOME}/bin/kubectl
cp `PWD`/config/admin.conf ${HOME}/.kube/config
```
2. You can add simple logic - install addons without configuring, only use helm provider for install helm charts. And may be add simple hooks after install chart. For example, after install dashboard search file `scripts/dashboars.sh` for executing with content:
```
#!/bin/bash
USER=baka
SPACE=kube-system

echo "Create a new account"
kubectl -n ${SPACE} create serviceaccount ${USER} >/dev/null 2>&1
echo "Add permissions to account"
kubectl create clusterrolebinding ${USER}-cluster-admin --clusterrole=cluster-admin --serviceaccount=${SPACE}:${USER} >/dev/null 2>&1
echo "Print token"
kubectl -n ${SPACE} describe secret $(kubectl -n ${SPACE} get secret | grep ${USER}-token | awk '{print $1}') | awk '$1=="token:"{print $2}'
```

**Comment by MusicDin** [comment]
Hi,

I disabled dashboard by default trough Kubespray addons and also managed to check MetalLB integration which I pushed in [integration-metallb branch](https://github.com/MusicDin/terraform-kvm-kubespray/tree/integration-metallb).

Currently only `layer2` protocol can be configured but I'm also looking forward to make a (virtual) solution for BGP protocol, which requires BGP enabled router.

If you have any suggestions how to integrate MetalLB with BGP protocol, please let me know.

There is also an option for custom `addons.yml` so that all Kubespray addons can be used until I slowly implement them into script.

**Comment by 6aKa** [comment]
Hi.
I put my example scripts in https://github.com/6aKa/kubespray-lxd.
config_machines.sh - create virtual machines with lxd, machines connected with bridge interface.
config_kubespray.sh - generate configuration for kubespray and run it.
config_cluster.sh - install dashboard with helm.

As I remember, that's all need for enable MetalLB with BGP
```
    sed -i -e '/metallb_enabled:/{s/^#\+\s//;s/false/true/;}' \
           -e '/metallb_ip_range:/,/metallb_version:/{/metallb_version:/!{s/^#\+\s//;}}' \
           -e '/metallb_protocol: "bgp"/{s/^#\+\s//;}' \
           -e '/metallb_peers:/{s/^#\+\s//;}' \
           -e '/metallb_peers:/a \  - peer_address: 10.10.10.1\n    peer_asn: 64501\n    my_asn: 64500' \
        ${GRPV}/k8s-cluster/addons.yml

    sed -i -e '/kube_proxy_strict_arp:/{s/^#\+\s//;s/false/true/;}' \
        ${GRPV}/k8s-cluster/k8s-cluster.yml
```
After that on host machine i install bird for bgp - with simple configuration like this
```
protocol bgp uplink0 {
      description "BGP uplink 0";
      local as 64501;
      neighbor 10.10.10.1 as 64500;
}
```
Sorry no original configuration

**Comment by MusicDin** [comment]
I've tried that configuration earlier today but seems like I misconfigured something, as BIRD won't connect to MetalLB and vice versa. 

From MetalLB perspective connection gets timed out and from BIRD's BGP is waiting for neighbor.

If I understand correctly, you connect router and cluster as 2 autonomous systems (with AS numbers 64501 and 64500), but why shouldn't it be one AS? I mean router is part of the cluster right?

Also you are connecting them trough network GW IP, so that's MetalLB and router's id?

May you open my eyes a bit by briefly explaining those things to me?

Thank you in advance.

**Comment by 6aKa** [comment]
You understand correctly, i use two AS. 

This image from inet describe idea of two AS
https://qiita-image-store.s3.amazonaws.com/0/42829/9ddf27ad-152b-06da-319c-8907e3e1cb34.png
image from article https://qiita.com/MahoTakara/items/a33c169b210fae2e8ec9

As i remember, metallb create new network interface on virtual machine, and i used gw from this new network as router id.

May be need add `passive yes;` to bird configuration.

You cat write small instruction for me, i setup cluster and configure.

**Comment by MusicDin** [comment]
Yeah, I would really need some help with it.

So let's imagine simple configuration with 1 master node and 2 worker nodes.
- Cluster's network: `192.168.113.0/24`
- Master node 1: `192.168.113.10/32`
- Worker node 1: `192.168.113.20/32`
- Worker node 2: `192.168.113.21/32`

MetalLB is configured in BGP mode and IP pool is `192.168.113.240/28` (192.168.113.241 - 192.168.113.254) which is subnet of cluster's network.
MetalLB ASN is `65100`

BGP router is BIRD with ASN `65000`

I'm especially intrested in BIRD configuration because in my case (with configuration provided above) MetalLB can't connect to router (timeout).

MetalLB gives correct addresses to running pods and those addresses are valid **within** nodes (if I SSH into them) but unreachable from host.

**Comment by 6aKa** [comment]
I try write configuration without testing.

```
metallb_enabled: true
metallb_ip_range:
  - "192.168.113.241 - 192.168.113.254"
metallb_version: v0.9.3
metallb_protocol: "bgp"
metallb_peers:
  - peer_address: 192.168.113.1
    peer_asn: 65000
    my_asn: 65100
```

```
router id 192.168.113.1;

protocol bgp uplink0 {
      description "BGP uplink 0";
      local as 65000;
      neighbor 192.168.113.1 as 65100;
      # metallb nodes connect to router, router only accept connections
      passive yes;

      #if i remember filters not need, get from example
      ipv4 {
              import filter {reject;};
              export filter {accept;};
      };
}
```

**Comment by MusicDin** [comment]
I tried almost same configuration with MetalLB version `v0.9.5` and your solution with versions from 0.9.3 - 0.9.5 and different CNI plugins. I enabled firewall for TCP port 179. Seems that problem is not related to MetalLB but to my (probalby host?) configuration. 

BIRD does not add any new route and MetalLB speaker constanly logs:
```
{"caller":"bgp.go:59","error":"dial \"192.168.113.1:179\": timeout","localASN":65100,"msg":"failed to connect to peer","op":"connect","peer":"192.168.113.1:179","peerASN":65000,"ts":"2021-02-01T22:18:40.319399921Z"}
```

I captured traffic on port 179, both on nodes and on host. Packages actually reach host but they don't seem to reach BIRD.

Could you maybe test the same configuration using this script? If it would work for you than I would expand it with BGP option so that others can use it.

**Comment by 6aKa** [comment]
No problem.
Can you write small instruction for that? like this
```
1. git clone...
...
x. set metallb_protocol 'bgp' in terraform.tfvars
...
y. set ... in kubespray_addons.tpl
...
z. terraform apply 
```

**Comment by MusicDin** [comment]
Sure.

```
 git clone https://github.com/MusicDin/terraform-kvm-kubespray.git -b integration-metallb
 cd terraform-kvm-kubespray/
```

Edit default addons file `defaults/addons.yml`, where you need to replace `metallb_enabled: false` at the bottom with:
```yaml
metallb_enabled: true
metallb_ip_range:
  - "192.168.113.241-192.168.113.254"
metallb_version: v0.9.3
metallb_protocol: "bgp"
metallb_peers:
  - peer_address: 192.168.113.1
    peer_asn: 65000
    my_asn: 65100
```

Deploy only 1 master and one or 2 workers (also change resources if needed).
In `terraform.tfvars` comment out:
```hcl
# Comment or remove both LBs
vm_lb_macs_ips = {
#  "52:54:00:00:00:05" = "192.168.113.5"
#  "52:54:00:00:00:06" = "192.168.113.6"
}

# Change floating IP to target master node 
vm_lb_vip = "192.168.113.10"

...

# Leave only one master
vm_master_macs_ips = {
  "52:54:00:00:00:10" = "192.168.113.10"
#  "52:54:00:00:00:11" = "192.168.113.11"
#  "52:54:00:00:00:12" = "192.168.113.12"
}

...

# Leave only one or two workers
vm_worker_macs_ips = {
  "52:54:00:00:00:40" = "192.168.113.100"
#  "52:54:00:00:00:41" = "192.168.113.101"
#  "52:54:00:00:00:42" = "192.168.113.102"
}

```

Apply:
```
terraform init
terraform apply
```

**Comment by 6aKa** [comment]
Hi. I checked. Problem with network configuration.
Be default open access to 53 and 67 port from vm to host, and from host to vm.
I try open 179 port with firewall-cmd, but failed. Than try open port with iptable rules, but failed.
Now i try find solution, need more time.

**Comment by MusicDin** [comment]
Firstly, I would like to thank you for taking your time.

It seems like there really is some issue with firewall which prevents host and vm talking over port 179.

I also tried opening a port via iptables but without any luck. Also, I can't tell you anything else as I didn't find a way to debug it or at least to find anything helpful after that. 
As I said before, I tried capturing traffic on host where I saw only BGP keepalive packages and BGP SYN packages on nodes.

**Comment by 6aKa** [comment]
Hi. I find time for investigation this problem.

For open trafic from host to vm need execute next commands
```
sudo firewall-cmd --permanent --zone=libvirt --add-service=bgp
sudo firewall-cmd --reload
```

Second problem with bird. Bird has two not compatible versions 1.6.X and 2.0.X. And i mistake in config. If neighbor equal router id - bird not listen 179 port.

Fixed bird.conf
```
router id 192.168.113.1;

protocol bgp uplink0 {
      description "BGP uplink 0";
      local as 65000;
      neighbor 192.168.113.10 as 65100;
      passive yes;

      ipv4 {
              import all;
              export all;
      };
}
```

And bird has implicit behavior - when some peers send wrong packets - bird block all incoming connections.
I catch this behavior using next order (if you want to reproduce):
1. turn off firewall `systemctl stop firewall`
2. turn off bird daemon `systemctl stop bird`
3. start bird from console `bird -c /etc/bird.conf -d` with fixed config
4. from vm run `telnet 192.168.113.1 179` - you see connection open - all ok.
5. wait 5 minutes - while all vm try connect to bgp router, when all failed - bird block connection for all
6. from vm run `telnet 192.168.113.1 179` - you see connection closed - bird block all.
7. if you stop and run bird from console, and after that try check connection with telnet - connection open and all good

**Comment by 6aKa** [comment]
I use equal peer_asn and my_asn for this configuration.
```
metallb_enabled: true
metallb_ip_range:
  - "192.168.113.241-192.168.113.254"
metallb_version: v0.9.3
metallb_protocol: "bgp"
metallb_peers:
  - peer_address: 192.168.113.1
    peer_asn: 65000
    my_asn: 65000
```

I uninstall bird, and install `frr` - all good and work fine.

1. install `frr`.
2. enable `bgp` in `/etc/frr/daemons`
3. start frr `systemctl --now enable frr`
4. check is running `ss -tunlp | grep 179`
5. make and write simple config from vtysh
```
localhost# show running-config
Building configuration...

Current configuration:
!
frr version 7.5
frr defaults traditional
hostname localhost
domainname
log file /var/log/frr/frr.log
no ipv6 forwarding
!
router bgp 65000
 coalesce-time 1000
 neighbor 192.168.113.10 remote-as 65000
 neighbor 192.168.113.11 remote-as 65000
 neighbor 192.168.113.12 remote-as 65000
 neighbor 192.168.113.100 remote-as 65000
 neighbor 192.168.113.101 remote-as 65000
 neighbor 192.168.113.102 remote-as 65000
!
line vty
!
end
localhost#
```
6. all neighbors connecting and active
```
localhost# show bgp summary

IPv4 Unicast Summary:
BGP router identifier 192.168.113.1, local AS number 65000 vrf-id 0
BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 6, using 128 KiB of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt
192.168.113.10  4      65000        59        62        0    0    0 00:28:35            0        0
192.168.113.11  4      65000        59        62        0    0    0 00:28:34            0        0
192.168.113.12  4      65000        59        62        0    0    0 00:28:34            0        0
192.168.113.100 4      65000        59        61        0    0    0 00:28:35            0        0
192.168.113.101 4      65000        59        61        0    0    0 00:28:36            0        0
192.168.113.102 4      65000        59        61        0    0    0 00:28:35            0        0

Total number of neighbors 6
localhost#
```

**Comment by MusicDin** [comment]
Thank you very much. 

I will try to implement that later today or tomorrow into the script. 

I suppose that firewall configuration is required in both cases?

**Comment by 6aKa** [comment]
Yes. Need open bgp traffic with firewall.

**Comment by 6aKa** [comment]
The investigation about bird describe why when after open bgp port i still getting "Connection closed by foreign host"

**Comment by pourgholi** [comment]
Hi,
any possibilities of providing any kind of dynamic storage provisioning ? 

I know that host path storage doesn't support dynamic provisioning.
I saw that there are possibilities of enabling  Ceph in Kubespay. But this requires servers. 
How does Minikibe does it ? Is it possible to enable some thing like that here to be able to test deployments which claim volumes without having to spin up storage servers ?

**Comment by MusicDin** [comment]
Hi,

you can use [Rancher's local-path-provisioner](https://github.com/rancher/local-path-provisioner) which is a dynamic provisioner.
You can configure it in `terraform.tfvars` in *Kubespray addons* section.

Other options are mostly based on network file systems as you have pointed out.

**Comment by pourgholi** [comment]
Nice. Ok. I'll try it. Thanks.
