### ISSUE TITLE
Activating MetalLB and Dashboard doesn't work for me 

### ISSUE THREAD

**Issue by pourgholi** [MusicDin/terraform-kvm-kubespray#7]
Hi,
this is more a question than an issue.
I created and the cluster from a fresh pull from your repo and only added Image and Distro in the terraform.tfvars file.
Everz thing works perfect and the cluster was created and i could kubectl and see and test averz thing as it is in the fresh master.

Then i tried to change the values in terraform.tfvars file :
1. Activate MetalLB: as described here:https://github.com/MusicDin/terraform-kvm-kubespray/blob/master/docs/examples/metallb.md#layer2
2. Activate Dashboard by changing the vaeriable values: k8s_dashboard_enabled = "true"

I created everzthing new again but i see none of them created. What am i missing ?

**Comment by MusicDin** [comment]
Hi,

I think the problem is because `kubespray_custom_addons_enabled` variable is set to `true`. This basically means that all variables below are ignored and file on `kubespray_custom_addons_path` is used instead  (which by default is [defaults/addons.yml](https://github.com/MusicDin/terraform-kvm-kubespray/blob/master/defaults/addons.yml)). 

To fix that, all you have to do is to set the variable `kubespray_custom_addons_enabled` to `false`.

I disabled this by default (see commit 6bd65e1), so now it should work out of the box.

If the issue remains, please let me know.

**Comment by pourgholi** [comment]
Hi,
Thanks a lot for the quick response, going to test it now.

**Comment by pourgholi** [comment]
Tested it and it works perfect. Thanks.
